services:
  - type: web
    name: mcd-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production