services:
  - type: web
    name: mcd-web-frontend
    env: static
    branch: main
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.15.1