services:
  - type: web
    name: mcd-web-frontend
    env: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    autoDeploy: true